// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policies.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPolicies = `-- name: AddPolicies :many
INSERT INTO policies(title, description, category)
SELECT
    unnest($1::text[]),
    unnest($2::text[]),
    unnest($3::text[])
RETURNING id, title, description, category, created_at, updated_at
`

type AddPoliciesParams struct {
	Titles       []string `json:"titles"`
	Descriptions []string `json:"descriptions"`
	Categories   []string `json:"categories"`
}

func (q *Queries) AddPolicies(ctx context.Context, arg AddPoliciesParams) ([]Policy, error) {
	rows, err := q.db.Query(ctx, addPolicies, arg.Titles, arg.Descriptions, arg.Categories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Policy
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const addPolicy = `-- name: AddPolicy :one
INSERT INTO policies(title, description, category)
VALUES($1, $2, $3)
RETURNING id, title, description, category, created_at, updated_at
`

type AddPolicyParams struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Category    string `json:"category"`
}

func (q *Queries) AddPolicy(ctx context.Context, arg AddPolicyParams) (Policy, error) {
	row := q.db.QueryRow(ctx, addPolicy, arg.Title, arg.Description, arg.Category)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addUserPolicies = `-- name: AddUserPolicies :many
INSERT INTO user_policies(user_id, policy_id)
SELECT
    unnest($1::UUID[]),
    unnest($2::UUID[])
RETURNING id, user_id, policy_id, created_at
`

type AddUserPoliciesParams struct {
	UserID   []pgtype.UUID `json:"user_id"`
	PolicyID []pgtype.UUID `json:"policy_id"`
}

func (q *Queries) AddUserPolicies(ctx context.Context, arg AddUserPoliciesParams) ([]UserPolicy, error) {
	rows, err := q.db.Query(ctx, addUserPolicies, arg.UserID, arg.PolicyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserPolicy
	for rows.Next() {
		var i UserPolicy
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PolicyID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const addUserPolicy = `-- name: AddUserPolicy :one
INSERT INTO user_policies(user_id, policy_id)
VALUES($1, $2)
RETURNING id, user_id, policy_id, created_at
`

type AddUserPolicyParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	PolicyID pgtype.UUID `json:"policy_id"`
}

func (q *Queries) AddUserPolicy(ctx context.Context, arg AddUserPolicyParams) (UserPolicy, error) {
	row := q.db.QueryRow(ctx, addUserPolicy, arg.UserID, arg.PolicyID)
	var i UserPolicy
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PolicyID,
		&i.CreatedAt,
	)
	return i, err
}

const deletePolicy = `-- name: DeletePolicy :exec
DELETE FROM policies
WHERE id = $1
`

func (q *Queries) DeletePolicy(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePolicy, id)
	return err
}

const getPolicies = `-- name: GetPolicies :many
SELECT id, title, description, category, created_at, updated_at FROM policies
ORDER BY category
`

func (q *Queries) GetPolicies(ctx context.Context) ([]Policy, error) {
	rows, err := q.db.Query(ctx, getPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Policy
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPoliciesByCategory = `-- name: GetPoliciesByCategory :many
SELECT id, title, description, category, created_at, updated_at FROM policies
WHERE category = $1
`

func (q *Queries) GetPoliciesByCategory(ctx context.Context, category string) ([]Policy, error) {
	rows, err := q.db.Query(ctx, getPoliciesByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Policy
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPolicyByID = `-- name: GetPolicyByID :one
SELECT  id, title, description, category, created_at, updated_at FROM policies
WHERE id = $1
`

func (q *Queries) GetPolicyByID(ctx context.Context, id pgtype.UUID) (Policy, error) {
	row := q.db.QueryRow(ctx, getPolicyByID, id)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPolicies = `-- name: GetUserPolicies :many
SELECT p.id, p.title, p.description, p.category, p.created_at, p.updated_at FROM policies p
INNER JOIN user_policies up ON up.policy_id = p.id
WHERE up.user_id = $1
ORDER BY category
`

func (q *Queries) GetUserPolicies(ctx context.Context, userID pgtype.UUID) ([]Policy, error) {
	rows, err := q.db.Query(ctx, getUserPolicies, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Policy
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPolicyIDs = `-- name: GetUserPolicyIDs :many
SELECT policy_id FROM user_policies
WHERE user_id = $1
`

func (q *Queries) GetUserPolicyIDs(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getUserPolicyIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var policy_id pgtype.UUID
		if err := rows.Scan(&policy_id); err != nil {
			return nil, err
		}
		items = append(items, policy_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserPolicy = `-- name: RemoveUserPolicy :exec
DELETE FROM user_policies
WHERE user_id = $1 AND policy_id = $2
`

type RemoveUserPolicyParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	PolicyID pgtype.UUID `json:"policy_id"`
}

func (q *Queries) RemoveUserPolicy(ctx context.Context, arg RemoveUserPolicyParams) error {
	_, err := q.db.Exec(ctx, removeUserPolicy, arg.UserID, arg.PolicyID)
	return err
}

const updatePolicy = `-- name: UpdatePolicy :one
UPDATE policies
SET 
    title = COALESCE($2, title),
    description = COALESCE($3, description),
    category = COALESCE($4, category),
    updated_at = now()
WHERE id = $1
RETURNING id, title, description, category, created_at, updated_at
`

type UpdatePolicyParams struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Category    string      `json:"category"`
}

func (q *Queries) UpdatePolicy(ctx context.Context, arg UpdatePolicyParams) (Policy, error) {
	row := q.db.QueryRow(ctx, updatePolicy,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Category,
	)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
