// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddPolicies(ctx context.Context, arg AddPoliciesParams) ([]Policy, error)
	AddPolicy(ctx context.Context, arg AddPolicyParams) (Policy, error)
	AddUserPolicies(ctx context.Context, arg AddUserPoliciesParams) ([]UserPolicy, error)
	AddUserPolicy(ctx context.Context, arg AddUserPolicyParams) (UserPolicy, error)
	ChangePassword(ctx context.Context, arg ChangePasswordParams) error
	CheckUserExistsViaEmail(ctx context.Context, email string) (bool, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeletePolicy(ctx context.Context, id pgtype.UUID) error
	GetPolicies(ctx context.Context) ([]Policy, error)
	GetPoliciesByCategory(ctx context.Context, category string) ([]Policy, error)
	GetPolicyByID(ctx context.Context, id pgtype.UUID) (Policy, error)
	GetUserDetails(ctx context.Context, email string) (GetUserDetailsRow, error)
	GetUserPolicies(ctx context.Context, userID pgtype.UUID) ([]Policy, error)
	GetUserPolicyIDs(ctx context.Context, userID pgtype.UUID) ([]pgtype.UUID, error)
	RemoveUserPolicy(ctx context.Context, arg RemoveUserPolicyParams) error
	UpdatePolicy(ctx context.Context, arg UpdatePolicyParams) (Policy, error)
	VerifyUserEmail(ctx context.Context, email string) (VerifyUserEmailRow, error)
}

var _ Querier = (*Queries)(nil)
