// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(name, email, password, phone_number, business_name, is_admin)
VALUES($1, $2, $3, $4, $5, $6)
RETURNING id, email, phone_number, business_name, is_admin created_at, updated_at
`

type CreateUserParams struct {
	Name         string `json:"name"`
	Email        string `json:"email"`
	Password     string `json:"password"`
	PhoneNumber  string `json:"phone_number"`
	BusinessName string `json:"business_name"`
	IsAdmin      bool   `json:"is_admin"`
}

type CreateUserRow struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PhoneNumber  string             `json:"phone_number"`
	BusinessName string             `json:"business_name"`
	CreatedAt    bool               `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.PhoneNumber,
		arg.BusinessName,
		arg.IsAdmin,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.BusinessName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyUser = `-- name: VerifyUser :exec
UPDATE users 
SET is_verified = TRUE
WHERE id = $1
`

func (q *Queries) VerifyUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, verifyUser, id)
	return err
}
