// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(name, email, password, phone_number, business_name, is_admin)
VALUES($1, $2, $3, $4, $5, $6)
RETURNING id, email, phone_number, business_name, is_admin, created_at, updated_at, verified, blacklisted
`

type CreateUserParams struct {
	Name         string `json:"name"`
	Email        string `json:"email"`
	Password     string `json:"password"`
	PhoneNumber  string `json:"phone_number"`
	BusinessName string `json:"business_name"`
	IsAdmin      bool   `json:"is_admin"`
}

type CreateUserRow struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PhoneNumber  string             `json:"phone_number"`
	BusinessName string             `json:"business_name"`
	IsAdmin      bool               `json:"is_admin"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Verified     bool               `json:"verified"`
	Blacklisted  bool               `json:"blacklisted"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.PhoneNumber,
		arg.BusinessName,
		arg.IsAdmin,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.BusinessName,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Verified,
		&i.Blacklisted,
	)
	return i, err
}

const verifyUserEmail = `-- name: VerifyUserEmail :one
UPDATE users 
SET verified = TRUE
WHERE email = $1
RETURNING id, email, phone_number, business_name, is_admin, created_at, updated_at, verified, blacklisted
`

type VerifyUserEmailRow struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PhoneNumber  string             `json:"phone_number"`
	BusinessName string             `json:"business_name"`
	IsAdmin      bool               `json:"is_admin"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Verified     bool               `json:"verified"`
	Blacklisted  bool               `json:"blacklisted"`
}

func (q *Queries) VerifyUserEmail(ctx context.Context, email string) (VerifyUserEmailRow, error) {
	row := q.db.QueryRow(ctx, verifyUserEmail, email)
	var i VerifyUserEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PhoneNumber,
		&i.BusinessName,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Verified,
		&i.Blacklisted,
	)
	return i, err
}
